const TaskActionTypes = {
  LOAD_TASK_START: "LOAD_TASK_START",
  LOAD_TASK_SUCCESS: "LOAD_TASK_SUCCESS",
  LOAD_TASK_FAIL: "LOAD_TASK_FAIL",
  CREATE_TASK_START: "CREATE_TASK_START",
  CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
  CREATE_TASK_FAIL: "CREATE_TASK_FAIL",
  DELETE_TASK_START: "DELETE_TASK_START",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_FAIL: "DELETE_TASK_FAIL",
  UPDATE_TASK_START: "UPDATE_TASK_START",
  UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
  UPDATE_TASK_FAIL: "UPDATE_TASK_FAIL",
  SET_TASK_EMPTY: "SET_TASK_EMPTY",
  SET_ERROR_MSG_EMPTY: "SET_ERROR_MSG_EMPTY",
  SET_EDIT_TASK: "SET_EDIT_TASK",
}

export default TaskActionTypes;